CREATE TABLE public.brand (
    brand_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name varchar(10) NOT NULL,
    use_yn varchar(1) NOT NULL,
    CONSTRAINT brand_pk PRIMARY KEY (brand_id)
);

CREATE TABLE public.category_price (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price integer NOT NULL,
    brand_id integer NOT NULL,
    category_type_id integer NOT NULL,
    CONSTRAINT category_pk PRIMARY KEY (id)
);

ALTER TABLE public.category_price ADD CONSTRAINT price_fk FOREIGN KEY (brand_id) REFERENCES public.brand(brand_id);

CREATE SEQUENCE "BRAND_SEQ"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1;

CREATE SEQUENCE "CATEGORY_SEQ"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1;